services:
  backend:
    image: $IMAGE
    ports:
      - "3334:3334"
    environment:
      - NODE_ENV=$NODE_ENV
      - API_PORT=$API_PORT
      - API_URL=$API_URL
      - DATABASE_URL=$DATABASE_URL
